### ISSUE TITLE
[Bug]: Fabric 1.20.1 - Cupboard no working + MidnightLib (Repurposed Structures mod) 

### ISSUE THREAD

**Issue by GitJhopa** [someaddons/cupboard#1]
### Describe the bug you're experiencing

server no starting

### Reproducability

place mod Cupboard and MidnightLib + Repurposed Structures mod

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric

### Logs

https://gist.github.com/GitJhopa/d52f0922a6272b3a23fa92967e4c2249

**Comment by someaddons** [comment]
fixed in 1.7
