### ISSUE TITLE
[Bug]: LegacyRandomSource Crash (seemingly w/AlexsCaves + EnhancedCelestials

### ISSUE THREAD

**Issue by NightmareRise** [someaddons/cupboard#12]
### Describe the bug you're experiencing

It first only happened in the Alex's Caves primordial caves biome. I tried to fly around and the game completely froze. Just recently it happened outside that biome. Cupboard is listed at the top of the log every single time. I do have a lot of other mods installed as this is a custom pack but the three listed in the title seem to be directly linked to it which is why I'm posting this here. I'll be contacting the other devs as well in case this is on their end.

### Reproducability

Install Alex's Caves, EC, and cupboard API. You will likely crash just by flying around generating chunks. It seems to have something to do with entity spawning?

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/NightmareRise/b81c707ef92476bb3eac5e4ea1dcd84a

**Comment by someaddons** [comment]
cupboard only makes the error log all current threads running, it itself does not use any randoms. If you want to avoid this issue I recommend to use my https://www.curseforge.com/minecraft/mc-mods/structure-essentials-forge-fabric mod
