### ISSUE TITLE
[Bug]: Cupboard detected as Malware 

### ISSUE THREAD

**Issue by Cramezzon** [someaddons/cupboard#14]
### Describe the bug you're experiencing

The mod "Cupboard" was detected as malware "Trojan:Script/Wacatac.B!ml" by anti-viruses I don't know if this is a false positive or not
![Screenshot 2024-03-10 183339](https://github.com/someaddons/cupboard/assets/162879658/02935504-85ed-4db5-9a5d-816d5c8e2811)

### Reproducability

It just got detected during a Virus scanning so I have no clear idea how this happened 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.2

### Modloader version

Forge

### Logs

https://gist.github.com/Cramezzon/9d398f29db109c6f230c804628cecff5

**Comment by someaddons** [comment]
pretty sure its a false positive, I just threw the 20.2 version on virus total: https://www.virustotal.com/gui/file/bf47c4455199d29e8c7b986fea282777764ce68c3a49dd3615a9f538e8d21429

**Comment by someaddons** [comment]
oh good question in this context, where did you download it from? The file I tested is from curseforge that should be safe

**Comment by Cramezzon** [comment]
It's downloaded from Curse Forge, the latest Release (During that time)

**Comment by someaddons** [comment]
ye that should be fine, best case its just a false positive, worst case you got some malware on your system that injects itself into jar files^^

**Comment by someaddons** [comment]
p.s. seems to be a common false positive these days, a bunch of other modders reported similar detections with their mods
