### ISSUE TITLE
[Bug]: Invalid mod icon {console spam)

### ISSUE THREAD

**Issue by Ketari-G** [someaddons/cupboard#16]
### Describe the bug you're experiencing

Upon loading the mod on fabric 1.20.1 or going into mod menu or really doing anything in-game that would get the game to request cupboard's icon, the game displays a question mark on a gray background and console gives this message:
[Render thread/ERROR]:
 Invalid mod icon for icon source cupboard: assets/icon.png
 java.nio.file.NoSuchFileException: /assets/icon.png
And also this:
[Render thread/WARN]:
 Warning! Mod cupboard has a broken icon, loading default icon
 

### Reproducability

Steps to reproduce issue:
1. Install fabric 1.20.1
2. Install mod menu
3. Install cupboard latest version (or any above 2.1)
4. Launch game and go into mod menu
5. Check game logs for error message

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric

### Logs

https://gist.github.com/Ketari-G/2e95b16a4e0da1d355e71ba971d61bde

**Comment by someaddons** [comment]
ye the mod doesnt ship an icon, nor does it need to. Not adding an icon just to make the mod menu mod look nice
