### ISSUE TITLE
[Bug]:  minecraft server constantly relaoding configs and spamming console

### ISSUE THREAD

**Issue by Nibbsiasek** [someaddons/cupboard#17]
### Describe the bug you're experiencing

My server is pernamently loading configs of 3 mods, dont know if its intended or not but it messes up console 

### Reproducability

anytime i start and run server

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

Forge 1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/Nibbsiasek/5b06aa7bd64d768ba63a1f71a1e0a53d

**Comment by someaddons** [comment]
Thats an issue with your server actually, the reload only happens when the files change, for some reason your server keeps flagging the files as changed
