### ISSUE TITLE
IMPORTANT - Trying to contact SomeAddons in order to request permission to include cupboard in my modpack.

### ISSUE THREAD

**Issue by notbrycem** [someaddons/cupboard#18]
IMPORTANT - Trying to contact SomeAddons in order to request permission to include cupboard in my modpack.

I've searched everywhere for contact info for you but I havent been able to.

So here I am. Please let me know if I can include cupboard in your pack.

thank you
![Screenshot 2024-09-16 230845](https://github.com/user-attachments/assets/0a2b4265-e697-47a3-8a52-8ec7104f8ce3)

**Comment by someaddons** [comment]
sorry I distribute my mods only on curseforge, feel free to upload it there
