### ISSUE TITLE
[Bug]: Datapacks break on lattest cupboard update for farbric 

### ISSUE THREAD

**Issue by Shibva** [someaddons/cupboard#2]
### Describe the bug you're experiencing

I tried to open a world and in the event of opening it, I got a datapack load error that prompted a return or enter "safe" mode.

### Reproducability

I am unsure but I think it has todo with datapacks being loaded through Openloader; though in what regard I'm unsure

It appears according to the log to be a few critical injection failures

if this issue needs to be reporducrable then ill be more then willing to provide the custom datapacks I put together/using to help fix this if nessisary

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

19.2

### Modloader version

Fabric

### Logs

https://gist.github.com/Shibva/fd3406b98b83ba8b637e9def8b4117dd

**Comment by someaddons** [comment]
fixed in 1.7
