### ISSUE TITLE
[Bug]: multiple threads

### ISSUE THREAD

**Issue by Damalas75** [someaddons/cupboard#21]
### Describe the bug you're experiencing

I was on my pack (could be my own fault) opened a Lan for Creative to check world generation and TP to a few structures. When loading up a Yung better Dungeons in game from a TP to check the structure I got a crash with this. I not sure myself what in the world happened it was working before updates So is it incompatible with xaero, artifacts  or Yungs since the updates?

I am also seeing Sinytra Connector ( Fabric to Forge connector)  could be an issue. 
Having issues locating the main cause cause it not even suppose to be "server" in a private test world (with Mods incompatible for a server to begin with.) It a mess since the mod updates.

### Reproducability

I have yet to be able to replicate it again, reloading it did not cause the error.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/Damalas75/2c3671ba599a85dfa299a024dc431e93

**Comment by someaddons** [comment]
ye that is unrelated to cupboard, it doesnt use randomsources. Its one of your mods using the randomsource on multiple threads at once, cupboard just has additional error logging for it. I actually have a mod that prevents that error, you could add it as a workaround: https://www.curseforge.com/minecraft/mc-mods/structure-essentials-forge-fabric
