### ISSUE TITLE
[Bug]: Heavy Conflicts with Fabric

### ISSUE THREAD

**Issue by A5ho9999** [someaddons/cupboard#3]
### Describe the bug you're experiencing

Cupboard seems to conflict and trigger crashes with many mods. Mainly with https://modrinth.com/mod/supermartijn642s-core-lib/version/1.1.12b-fabric-mc1.20 much like #1 

### Reproducability

Place Cupboard with supermartijn642s-core-lib and other mods, in this log - https://modrinth.com/mod/noexpensive/version/1.20.1-1.9.0

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric

### Logs

https://gist.github.com/A5ho9999/fe7337fa0fa3b0ea1cce7f5c12a5a3b5

**Comment by someaddons** [comment]
fixed in 1.7
