### ISSUE TITLE
[Bug]: 1.19.2 forge incompatibility with dimensional threading

### ISSUE THREAD

**Issue by RexkUr** [someaddons/cupboard#4]
### Describe the bug you're experiencing

adding dimensional threading reforged and the cupboard api mod causes the game to spawn an excessive amount of mobs 1000+

### Reproducability

with the two mods installed run around and eventually you will find excessive amounts of mobs spawning causing the client and server to lag 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

https://pastebin.com/RRMXTPbW

**Comment by someaddons** [comment]
dimensional threading is not supported and should never be used with other mods, the concept straight out does not work in a modded environment

**Comment by CCr4ft3r** [comment]
Even though I'm not the owner of DimThread (just ported it to Forge) I just want to say that this is not true. 
DimThread is actually working fine with a lot of mods (probably with most). But it can only work with those considering that a multithreaded environment can exist or those who are implemented thread-safe.

**Comment by Reshy** [comment]
This really needs to be readdressed.

**Comment by retropele** [comment]
> Even though I'm not the owner of DimThread (just ported it to Forge) I just want to say that this is not true. DimThread is actually working fine with a lot of mods (probably with most). But it can only work with those considering that a multithreaded environment can exist or those who are implemented thread-safe.

I'd like to reiterate this, I'm running a game with 400+ mods and Dimensional Threading has never caused an issue for me (even C2ME auto-disables a setting to be compatible with DimThread, and runs like butter).

But I would love for Cupboard to be compatible, it's the only mod I've used that's outright incompatible and it would enable a couple of mods on my mod wishlist. :)

**Comment by WaffleDevs** [comment]
Is this incompatibility also in the 1.18.2 versions?
