### ISSUE TITLE
Bug with only performance mods installed

### ISSUE THREAD

**Issue by MadDifferentMethods** [someaddons/cupboard#5]
Weird bug with this mod installed, spawns a lot of mobs around the player in ocean once the player uses a egg spawner.
![modlist](https://github.com/someaddons/cupboard/assets/137194521/53a29fa1-f7ee-4fa8-b9a9-72a59a0844f2)
Only performance mods installed.
Steps to reproduce: 
1. Install forge 43.3.2.
2. Install mods shown + Cupboard(it's not in the picture).
3. Create new world.
4. Go to nearest ocean or big water body.
5. Use any Spawner Egg.
It should instantly spawn a ton of squids and fish around the player.

**Comment by MadDifferentMethods** [comment]
I also should mention that it makes the world generation hang a lot while first generating, have to wait at least 2-3 minutes for entire chunks to appear and I don't think it's because of my pc, I have 32GB of ram with ryzen 7 5800x.

**Comment by someaddons** [comment]
Please upload your log file from logs/latest.log to https://gist.github.com/ and put in the link below. It always contains needed, important information.

**Comment by someaddons** [comment]
Dimensional threading is not supported
