### ISSUE TITLE
[Crash]: Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by KostromDan** [someaddons/cupboard#6]
### Describe the bug you're experiencing

Second time experiencing random crash after few seconds after entering the world/server.
[crash-2023-10-14_13.15.44-client.txt](https://github.com/someaddons/cupboard/files/12904418/crash-2023-10-14_13.15.44-client.txt)

### Reproducability

M-Tech modpack 1.6.4.
But crash is random.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

https://gist.github.com/KostromDan/584a3ef0f38bb373c8d5525c2404afe4

**Comment by someaddons** [comment]
cupboard does use any randoms at all.
