### ISSUE TITLE
[Bug]: Client and Server Fail to Load Cupboard

### ISSUE THREAD

**Issue by MadSciSlack** [someaddons/cupboard#7]
### Describe the bug you're experiencing

When trying to add Cupboard with Connectivity, I get the following error:

[main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'cupboard', Requested by: 'connectivity', Expected range: '[1.19.2-1.5,)', Actual version: '[MISSING]'
	
and even after multiple launch events:

[main/WARN] [mixin/]: Error loading class: com/cupboard/config/CupboardConfig (java.lang.ClassNotFoundException: com.cupboard.config.CupboardConfig)

The 2nd error is the last error in the log.  I got similar errors server-side when I tried it there about not finding Cupboard or its config.
	
Cupboard is definitely installed, visible in the list, and at the latest version.  Is there a workaround for this, or any insight you can provide on why it won't locate Cupboard?

Let me know how else I can help, and I'll do my best.

### Reproducability

Issue happens every time I launch with Connectivity & Cupboard installed.  Removing both fixes the issue completely.  The failure occurs very early in the loading process.

I've reviewed the log included in the GIST, and other errors about things missing are normal.  These are from mods that have optional compatibility with the listed missing items.  For the past year, they've not caused any crashes or actual issues.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

https://gist.github.com/MadSciSlack/12bb3d85d6af575d7637835622bed865

**Comment by MadSciSlack** [comment]
**Further Information:** Rolling Cupboard back to V1.9 and Connectivity to V4.5 allows my client pack to load.  It would appear that it's an issue in the latest version, or perhaps V2.0+.  I did not try V2.0, rather went straight to the August 2023 releases for both mods as I knew they would pair properly.

I haven't tried zapping it back in server-side yet, but I imagine that this version will work based on what I've just witnessed.

Hopefully this helps.

Cheers,

Slack
(Pack Dev, Scripter, Mad Scientist)

**Comment by someaddons** [comment]
can't reproduce the issue with connectivity 4.6 and cupboard 2.1 for forge 1.19.2, make sure you got exactly those versions installed^^

**Comment by MadSciSlack** [comment]
I've tried with the latest version on more than one occasions with the same result, but I may try again when I find some time.  The V1.9 / V4.5 combination is working in the meantime, both server and client side.

Best regards,

Slack

**Comment by someaddons** [comment]
I suspect your launcher may have not properly installed/deleted the old versions then, which may have caused the issue
