### ISSUE TITLE
[Bug]: [1.20.2] Is future NeoForge support planned?

### ISSUE THREAD

**Issue by SanteriLoitomaa** [someaddons/cupboard#8]
### Describe the bug you're experiencing

From 1.20.2 onwards NeoForge is no longer the same as Forge and is going to need its own version. This mod will crash Minecraft 1.20.2 immediately if you try to start it with NeoForge.

Failure message: Mod File cupboard-1.20.2-2.1.jar needs language provider javafml:36 or above to load
We have found 1.0

Please remove the NeoForge label from your Modrinth/Curse Forge 1.20.2 releases until NeoForge is actually supported.

### Reproducability

Open latest mod version with the latest NeoForge.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.2

### Modloader version

Forge

### Logs

https://gist.github.com/SanteriLoitomaa/2b9c2d5787323b277e9121030f900fd7

**Comment by someaddons** [comment]
Removed it, neoforge is planned eventually, it just came out
