### ISSUE TITLE
[Bug]: Adding Cupboard mod (v1.20.1-2.2) as a dependency for Connectivity still throws error

### ISSUE THREAD

**Issue by michaelScopic** [someaddons/cupboard#9]
### Describe the bug you're experiencing

I am using the DarkRPG server mod pack and included the connectivity mod. 
I added the Cupboard library to the `mods/` when it complained about a missing dependency and ran the start script which gave the same error as before I added the lib. 

Here are my JVM args, if needed:
```java
-Xmx6G -Xms6G -XX:+UseG1GC -XX:MaxGCPauseMillis=130 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=28 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=20 -XX:G1MixedGCCountTarget=3 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcMarkStepDurationMillis=5 -XX:G1ConcRSHotCardLimit=16 -XX:G1ConcRefinementServiceIntervalMillis=150
```
TTY logs are here (and proof that `cupboard.jar` is in `mods/`):
![image_2024-01-09_151821807](https://github.com/someaddons/connectivity/assets/67214805/3e54697a-78cf-4971-b9e1-c11a6f5b8629)

### Reproducability

Run the included `start.sh` with `connectivity-fabric-1.20.1-4.9.jar` and `cupboard-1.20.1-2.2.jar` in the `mods/` directory. 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric

### Logs

https://gist.github.com/michaelScopic/b3375cf12b855b112added8b0131e56d

**Comment by someaddons** [comment]
`cupboard-1.20.1-2.2.jar` is the forge version of cupboard

**Comment by michaelScopic** [comment]
Just added the correct file, and tried the startup again but gave a new error. 

[latest.log](https://github.com/someaddons/cupboard/files/13935450/latest.log)

**Comment by someaddons** [comment]
you've got the timeout mod which isnt needed/not compatible with connectivity as it covers the same functionality and more. As also mentioned on connectivities page^^
